- hosts: "*"
  become: true
  become_user: chuck
  tasks:
    - name: Remove apt lock file
      ansible.builtin.file:
      state: absent
      path: "/var/lib/dpkg/lock-frontend"
      
    - name: apt
      apt:
        update_cache: yes
       # upgrade: 'yes'
