---
- name: Update and upgrade packages on debian based systems
  hosts: all
  #become: true
  #become_method: sudo
  #become_user: chuck
  
  tasks:
    - name: Update apt cache and upgrade packages
      #become: true
      #become_user: chuck
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        name: "*"
        state: latest        
        
