---
- name: Update and upgrade packages on debian based systems
  hosts: all
  #become: true
  #become_method: sudo
  #become_user: chuck

  vars:
    ansible_ssh_private_key_file: "/root/.ssh/ans_rsa.pub"
    ansible_sudo_pass: "Mon4381ica"
  
  tasks:
    - name: Update apt cache and upgrade packages
      #become: true
      #become_user: chuck
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        name: "*"
        state: latest        
        
