---
- name: Update cache and packages
  hosts: all
  gather_facts: no
  become: true

  tasks:
  - name: Update APT Cache
    ansible.builtin.apt:
      name: "*"
      state: latest
      force_apt_get: yes

  - name: Remove apt lock file
    ansible.builtin.file:
      state: absent
      path: "/var/lib/dpkg/lock-frontend"

  - name: Upgrade all packages to the latest version
    ansible.builtin.apt:
      upgrade: dist
      force_apt_get: yes   
        
