---
- name: Update cache and packages
  hosts: all
  gather_facts: no
  become: true
  #become_user: chuck

  tasks:
  - name: Update APT Cache
    ansible.builtin.apt:
      name: "*"
      state: latest
      force_apt_get: yes

  - name: Remove apt lock file
    ansible.builtin.file:
      state: absent
      path: "/var/lib/dpkg/lock-frontend"

  - name: Upgrade all packages to the latest version
    ansible.builtin.apt:
      upgrade: dist
      force_apt_get: yes

  - name: Check if system reboot is required
#      become: true
    ansible.builtin.stat:
      path: /run/reboot-required
    register: reboot_required

  - name: Report if reboot is required
    ansible.builtin.debug:
      msg: "Reboot is required"
    when: reboot_required.stat.exists      
        
