---
- name: Update and upgrade packages on debian based systems
  hosts: all
  become: true
  tasks:
    - name: Update apt cache and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: full

