---
- name: Update and upgrade packages on debian based systems
  hosts: all
  become: true
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      ansible.builtin.apt:
        update_cache: yes
        upgrade: full

