---
- name: Update APT Cache
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes

- name: Remove apt lock file
  ansible.builtin.file:
    state: absent
    path: "/var/lib/dpkg/lock"

- name: Upgrade all packages to the latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    force_apt_get: yes   
        
